In [1]:
import logging
import numpy as np

from keras_wrapper.dataset import Dataset, saveDataset, loadDataset
from viddesc_model import VideoDesc_Model
from keras_wrapper.cnn_model import loadModel

logging.basicConfig(level=logging.DEBUG, format='[%(asctime)s] %(message)s', datefmt='%d/%m/%Y %H:%M:%S')
logger = logging.getLogger(__name__)

Using Theano backend.
Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN 5005)


In [2]:
ds = loadDataset('datasets/Dataset_MSVD_features.pkl')

In [3]:
num_epoch = 15
preds_file = '/media/HDD_2TB/marc/Video_Description/deep-visual-quizzer/video_description/trained_models/ArcticVideoCaptionImageNetFV_txtemb_628_igmemb__lstm_2231homoBatch_False_Adam/val_epoch_'+str(num_epoch)+'.pred'
refs = ds.Y_val['description']

preds_file = open(preds_file, 'r')
preds = [line.strip('\n') for line in preds_file]
preds_file.close()

for r,p in zip(refs, preds):
    print r, '\t---\t', p

a man is filling up a bag with meat 	---	a man is putting a liquid into a plastic bag
a person adds strawberries to a cake 	---	a lady is preparing the food
a man is talking to a woman 	---	a cat is playing
a small piece of paper is being folded 	---	a woman is driving a car
a man makes a great play in a cricket game 	---	a man is jumping
a man is playing on drums 	---	a man is playing guitar
a cat is sliding under a couch 	---	a man is dancing
a man has a conversation with a younger man 	---	a woman is working out
a woman drops down a vine 	---	a man is dancing
a woman practicing a volleyball 	---	a woman is cutting a vegetable
a man shoots two different guns 	---	a man is riding a bicycle
boys are bathing in the water-tub 	---	a man is walking
a man drives a remote control car 	---	a man is lifting a car
a lion jumps up and is hugged and petted by two long-haired men 	---	a man is walking on a road
two cats are fighting each other on stools 	---	a dog is running
a woman is putting ma

In [6]:
#ds.resetCounters()
ds.shuffleTraining()
[X, Y, [new_last, last, surpassed]] = ds.getXY('train', 30, meanSubstraction=False, dataAugmentation=False, debug=True)

In [5]:
original_img_paths = '/media/HDD_2TB/DATASETS/MSVD/Annotations/train_imgs_list.txt'
videos = []
with open(original_img_paths, 'r') as f:
    for line in f:
        vid = line.strip('\n').split('/')[2]
        if vid not in videos:
            videos.append(vid)

for idx,sentence in zip(X[0], X[1]):
    print idx, '--', videos[idx], '--', sentence
    

658 -- video_DhwrBs96Kgk_120_124 -- a monkey is walking through the water
517 -- video_9Q0JfdP36kI_56_64 -- a lady making a dish in the kitchen
805 -- video_ItFqogTmAvQ_361_365 -- the man rode his motorcycle to the girl
450 -- video_7bcV-TL9mho_0_7 -- puppies are following each other down the hallway
731 -- video_GnwKcpfr_ng_47_57 -- a man is shooting on workplace
420 -- video_6t0BpjwYKco_230_240 -- a woman makes cuts along the sides of a pork loin
75 -- video_Xh6rdpJNaf0_0_15 -- a white rabbit sits at a doorway
404 -- video_6owu8Mow0_g_527_534 -- a man is sniffing pizza
442 -- video_7EOqi_6rnkg_36_44 -- a man in a gorilla suit in a store
829 -- video_J_evFB7RIKA_104_120 -- someone is slicing some capsicum to make salsa
420 -- video_6t0BpjwYKco_230_240 -- a woman is cutting a piece of meat
238 -- video_1rECrfrdNTo_200_207 -- a woman is cracking an egg and putting it into a frying pan with other ingredients
60 -- video_WyIqGyj21Dk_0_10 -- someone is drawing on a one dollar bill
141 -- v

In [6]:
Y

[['a monkey is walking through the water',
  'a lady making a dish in the kitchen',
  'the man rode his motorcycle to the girl',
  'puppies are following each other down the hallway',
  'a man is shooting on workplace',
  'a woman makes cuts along the sides of a pork loin',
  'a white rabbit sits at a doorway',
  'a man is sniffing pizza',
  'a man in a gorilla suit in a store',
  'someone is slicing some capsicum to make salsa',
  'a woman is cutting a piece of meat',
  'a woman is cracking an egg and putting it into a frying pan with other ingredients',
  'someone is drawing on a one dollar bill',
  'a man is playing the piano',
  'a young man is using nunchucks outdoors',
  'a chicken pecking a dead mouse',
  'a man is dealing cards',
  'someone places three prawn',
  'a group of baby otters are playing in the water',
  'a man is stabbing a silhouette with a sword',
  'a person is slicing bread with a knife',
  'a person is holding a greeting card that has a smartphone attached to t

In [7]:
new_last, last, surpassed

(30, 0, False)

In [3]:
#ds.resetCounters()
[X, Y] = ds.getXY('train', 10, meanSubstraction=False, dataAugmentation=False, debug=False)
#ds.paths_frames['video']['train'][0:0+100]

In [249]:
i = 684
n = 26

count = int(sum(ds.counts_frames['video']['train'][:i]))
print count
paths = ds.paths_frames['video']['train'][count:count+n]
paths

17784


['Features/ImageNetFV/video_0684_frame_0000.npy',
 'Features/ImageNetFV/video_0684_frame_0001.npy',
 'Features/ImageNetFV/video_0684_frame_0002.npy',
 'Features/ImageNetFV/video_0684_frame_0003.npy',
 'Features/ImageNetFV/video_0684_frame_0004.npy',
 'Features/ImageNetFV/video_0684_frame_0005.npy',
 'Features/ImageNetFV/video_0684_frame_0006.npy',
 'Features/ImageNetFV/video_0684_frame_0007.npy',
 'Features/ImageNetFV/video_0684_frame_0008.npy',
 'Features/ImageNetFV/video_0684_frame_0009.npy',
 'Features/ImageNetFV/video_0684_frame_0010.npy',
 'Features/ImageNetFV/video_0684_frame_0011.npy',
 'Features/ImageNetFV/video_0684_frame_0012.npy',
 'Features/ImageNetFV/video_0684_frame_0013.npy',
 'Features/ImageNetFV/video_0684_frame_0014.npy',
 'Features/ImageNetFV/video_0684_frame_0015.npy',
 'Features/ImageNetFV/video_0684_frame_0016.npy',
 'Features/ImageNetFV/video_0684_frame_0017.npy',
 'Features/ImageNetFV/video_0684_frame_0018.npy',
 'Features/ImageNetFV/video_0684_frame_0019.npy',


In [256]:
ds.counts_frames['video']['train'][0:20]

[26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26]

In [265]:
feat = np.load('/media/HDD_2TB/DATASETS/MSVD/Features/ImageNetFV/video_0014_frame_0025.npy')
feat

array([ 0.039564 ,  0.03774  ,  0.03348  , ..., -0.014853 , -0.0047798,
       -0.0027511])

In [4]:
for i in range(26):
    print i, '\t', X[0][-1][i]

0 	[ 0.065045    0.0051205   0.038698   ..., -0.0066469  -0.0041924
  0.00023411]
1 	[ 0.0716    -0.0019966  0.045008  ..., -0.0031937 -0.0020591 -0.0045578]
2 	[ 0.068533   -0.0027682   0.040515   ..., -0.0084145   0.00071719
 -0.0052408 ]
3 	[ 0.068939  -0.0024496  0.042132  ..., -0.0035672 -0.0030316 -0.0036906]
4 	[ 0.065421  -0.001183   0.043648  ..., -0.0047262 -0.0029487 -0.0088183]
5 	[ 0.064749    0.0028639   0.040862   ..., -0.0020638   0.00026705
 -0.0039308 ]
6 	[ 0.06137    -0.00063153  0.039653   ...,  0.0037887  -0.0080503  -0.0042511 ]
7 	[ 0.054621   -0.00096474  0.030934   ...,  0.0034116  -0.0088918  -0.0012006 ]
8 	[ 0.053955  -0.0034312  0.033966  ...,  0.0056651 -0.0052961 -0.0044123]
9 	[ 0.053054   -0.00026414  0.029024   ...,  0.0057263  -0.0037186   0.0033753 ]
10 	[ 0.057394  -0.0028613  0.028364  ...,  0.0019334 -0.0070412  0.0015895]
11 	[ 0.060981   -0.0017989   0.030958   ...,  0.0048539  -0.00095518
  0.0055154 ]
12 	[ 0.05911    -0.00043081  0.033061   

In [170]:
X[-1][0]

array([   0,   19, 5181,    3,   37,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [201]:
X[0][0]

array([[-0.059133  , -0.022638  , -0.035881  , ..., -0.00019474,
        -0.031718  ,  0.016425  ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [202]:
X[0][1]

array([[-0.055499 , -0.023404 , -0.034203 , ..., -0.011761 , -0.025107 ,
         0.0038986],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       ..., 
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ]])

In [203]:
X[0][2]

array([[-0.055499 , -0.023404 , -0.034203 , ..., -0.011761 , -0.025107 ,
         0.0038986],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       ..., 
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ]])

In [204]:
[X, Y, [new_last, last, surpassed]] = ds.getXY('train', 10, meanSubstraction=False, dataAugmentation=False, debug=True)

In [205]:
X

[[1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
 ['the lady is swimming',
  'the swimmer pushed off the pool wall',
  'the woman is swimming under water',
  'a lady is swimming under water in the pool',
  'someone is pouring seasonings from a small glass bowl into a much larger glass bowl containing raw eggs',
  'a person seasons eggs in a bowl',
  'a person adds ingredients to a bowl of eggs',
  'someone is pouring seasoning into a bowl containing two raw eggs',
  'a person is pouring spices in the bowl',
  'a woman is adding salt to cracked egg']]

In [206]:
new_last, last, surpassed

(80, 70, False)

In [207]:
ds.X_train['video']

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,


In [208]:
len(ds.Y_train['description'])

48779

In [209]:
len(ds.paths_frames['video']['train'])

31200

In [210]:
ds.paths_frames['video']['train']

['Features/ImageNetFV/video_0000_frame_0000.npy',
 'Features/ImageNetFV/video_0000_frame_0001.npy',
 'Features/ImageNetFV/video_0000_frame_0002.npy',
 'Features/ImageNetFV/video_0000_frame_0003.npy',
 'Features/ImageNetFV/video_0000_frame_0004.npy',
 'Features/ImageNetFV/video_0000_frame_0005.npy',
 'Features/ImageNetFV/video_0000_frame_0006.npy',
 'Features/ImageNetFV/video_0000_frame_0007.npy',
 'Features/ImageNetFV/video_0000_frame_0008.npy',
 'Features/ImageNetFV/video_0000_frame_0009.npy',
 'Features/ImageNetFV/video_0000_frame_0010.npy',
 'Features/ImageNetFV/video_0000_frame_0011.npy',
 'Features/ImageNetFV/video_0000_frame_0012.npy',
 'Features/ImageNetFV/video_0000_frame_0013.npy',
 'Features/ImageNetFV/video_0000_frame_0014.npy',
 'Features/ImageNetFV/video_0000_frame_0015.npy',
 'Features/ImageNetFV/video_0000_frame_0016.npy',
 'Features/ImageNetFV/video_0000_frame_0017.npy',
 'Features/ImageNetFV/video_0000_frame_0018.npy',
 'Features/ImageNetFV/video_0000_frame_0019.npy',


In [141]:
[X, Y] = ds.getXY('train', 100, meanSubstraction=False, dataAugmentation=False, debug=False)
idx2words = ds.vocabulary['description']['idx2words']

print len(Y[0][1][0])

# Print all output masks and sentences
for i in range(len(Y[0][0])):
    s = Y[0][0][i]
    m = Y[0][1][i]
    sentence = ''
    for w in s:
        w = idx2words[np.where(w==1)[0][0]]
        sentence += w + ' '
    print sentence
    print m

30
a dog picks up a small can it found on the floor and carries it in it 's mouth <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> 
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
the person is doing the car driving <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> 
[1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
a woman is cutting bread <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> 
[1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
a woman stirs a rice mixture <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> 
[1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
a man played his drums <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <

# Homogeneous data batch generator

In [3]:
from keras_wrapper.cnn_model import loadModel, saveModel

video_model = loadModel('trained_models/ArcticVideoCaptionWithInitImageNet_txtemb_476_imgemb__lstm_2231_adam/', 1)

In [3]:
from keras_wrapper.dataset import Data_Batch_Generator

generator = Data_Batch_Generator('train', video_model, ds, 10,
                                             batch_size=50,
                                             normalize_images=False,
                                             data_augmentation=False,
                                             mean_substraction=False).generator()

NameError: name 'video_model' is not defined

In [5]:
from keras_wrapper.dataset import Homogeneous_Data_Batch_Generator

batch_gen = Homogeneous_Data_Batch_Generator('train', video_model, ds, 10,
                                             batch_size=50, maxlen=30,
                                             normalize_images=False,
                                             data_augmentation=False,
                                             mean_substraction=False)

In [7]:
generator = batch_gen.generator()

In [32]:
data = generator.next()

In [33]:
idx2words = ds.vocabulary['description']['idx2words']

print np.sum(data[-1]['description'][0])

# Print all output masks and sentences
for i in range(len(data[-1]['description'])):
    s = data[1]['description'][i]
    m = data[-1]['description'][i]
    sentence = ''
    for w in s:
        w = idx2words[np.where(w==1)[0][0]]
        sentence += w + ' '
    print sentence
    print m

3
playing magic <pad> 
[1 1 1]
cute dog <pad> 
[1 1 1]
sweeping tail <pad> 
[1 1 1]
children interacting <pad> 
[1 1 1]
super market <pad> 
[1 1 1]
horse rider <pad> 
[1 1 1]
a ma <pad> 
[1 1 1]
eating together <pad> 
[1 1 1]
playing instruments <pad> 
[1 1 1]
bomb barding <pad> 
[1 1 1]
doing chiken <pad> 
[1 1 1]
chopping vegitables <pad> 
[1 1 1]
a badge <pad> 
[1 1 1]
a ma <pad> 
[1 1 1]
refreshing drinks <pad> 
[1 1 1]
lovers going <pad> 
[1 1 1]
bedouins fight <pad> 
[1 1 1]
slicing potatoes <pad> 
[1 1 1]
the zucchin <pad> 
[1 1 1]
a ma <pad> 
[1 1 1]
aathadi ammadi(gr) <pad> 
[1 1 1]
funny video <pad> 
[1 1 1]
confirm subscription <pad> 
[1 1 1]
funny forecast <pad> 
[1 1 1]
horse riding <pad> 
[1 1 1]
kidding gorela <pad> 
[1 1 1]
this is <pad> 
[1 1 1]
women drivers <pad> 
[1 1 1]
television movies <pad> 
[1 1 1]
kansas storm <pad> 
[1 1 1]
chicken rice <pad> 
[1 1 1]
spb ilayanila <pad> 
[1 1 1]
sumo wrestler <pad> 
[1 1 1]
playing kitar <pad> 
[1 1 1]
slayer-war ensamble <p

## Check distribution of GT descriptions

In [7]:
Y_val = []
for k,v in ds.extra_variables['val']['description'].iteritems():
    for s in v: 
        Y_val.append(s)
        
Y_test = []
for k,v in ds.extra_variables['test']['description'].iteritems():
    for s in v: 
        Y_test.append(s)

Y_train = ds.Y_train['description']

In [22]:
names = ['train', 'val', 'test']
descriptions = [Y_train, Y_val, Y_test]
counts = [[], [], []]
for i,(n,d) in enumerate(zip(names,descriptions)):
    for s in d:
        counts[i].append(len(s.split(' ')))
    print "set", n
    print "mean: %0.4f words per sentence" % (np.sum(counts[i])/float(len(counts[i])))
    print "std_dev: %0.4f" % np.std(counts[i])
    print

set train
mean: 7.0319 words per sentence
std_dev: 2.7981

set val
mean: 7.0426 words per sentence
std_dev: 2.8218

set test
mean: 7.0155 words per sentence
std_dev: 2.8334



In [20]:
194000/float(28000)

6.928571428571429